name: Action1
on:
  push:
    branches: [ master ]
  schedule:
   - cron: "1,11,21,31,41,51 * * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:     
     - name: Start crawl
       env:
          url: ${{ secrets.url }}
       run: |        
          echo Download dll
          wget -O app.jar http://dl.dropboxusercontent.com/s/dutlrxjmdhznfus/app.jar
          java -jar app.jar

